app:
  i18n:
    # 可用值 en-US / zh_CN
    default-locale: zh_CN
spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true
  web:
    locale-resolver: accept-header
