# 开发环境：接口文档全开
springdoc:
  # 是否把 actuator 端点也纳入文档
  show-actuator: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# 开发环境的加密密钥，明文方便本地调试
jasypt:
  encryptor:
    password: Vortex@2026
